### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by minhnimble** [M-I-N/NimbleSurvey#9]
Hello Nayem 👋 , thank you for your effort on the code submission. I am Mike, acting as an Engineer Lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process and I would love to hear back from you as well. Therefore, don’t hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

**Comment by minhnimble** [comment]
Hello Nayem again 👋, I complete my review round just now. Please go ahead and provide your feedback on all my proposed issues.

Just for your information, we expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us right away so that we can plan accordingly.

Have a great day! ☀️

**Comment by M-I-N** [comment]
Hi @minhnimble 

Thank you for bringing up the concerns regarding the assignment. I've commented on some issues and also tried to show my ideas. Other than these, I implemented and enhanced some features you were concerned about. 

Please take your time to check. In the meantime I'll try to comment on any remaining issue. 

Cheers!

**Comment by minhnimble** [comment]
Good afternoon Nayem 👋

Thank you for your thorough answers on the given issues! Just now, I complete checking and replying to some of the issues that need further attentions. You can go ahead and provide your feedback on my new comments if needed. 👍

Regards!

**Comment by minhnimble** [comment]
Good afternoon @M-I-N  ☀️

As of this point, since there is no new update from your side, this code challenge review session reaches a conclusion and no further discussion will be needed from your end. About the next step, you will be hearing from the Talent Acquisition team about the decision as soon as possible. 🙏

In the end, it was a pleasure reviewing your code and getting to know you. Thanks for your time and I wish you all the best! 🍀

**Comment by M-I-N** [comment]
Hello @minhnimble 

My apologies as I couldn't respond earlier. I was actually out of town and away from internet. 

Whatever, thank you for your time and queries as they pushed me understand some aspects once again. But I am just curious to know more regarding one thing at #10. If you have time please checkout and help me in any way you can. 

Thank you 🙏🏽
